// <auto-generated />
namespace Contoso.Commerce.RetailProxy.Extension
{
    using System;
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using Microsoft.Dynamics.Commerce.RetailProxy;
    using Microsoft.Dynamics.Commerce.RetailProxy.Adapters;
    using Microsoft.OData.Client;
    
    /// <summary>
    /// ExampleEntity entity class.
    /// </summary>
    [Microsoft.OData.Client.Key("UnusualEntityId")]
    [GeneratedCodeAttribute("Contoso.Commerce.RetailProxy.Extension", "1.0")]
    public class ExampleEntity : CommerceEntity
    { 
        /// 
        /// Initializes a new instance of the <see cref="ExampleEntity" /> class.
        /// 
        public ExampleEntity()
        {
            
            this._extensionProperties.CollectionChanged += ExtensionProperties_OnCollectionChanged;
        }
      
        /// <summary>
        /// Gets or sets the IntData.
        /// </summary>
        public int IntData
        {
            get
            {
                return this._intData;
            }
        
            set
            {
                this._intData = value;
                this.OnPropertyChanged("IntData");
            }
        }
      
        private int _intData;
      
        /// <summary>
        /// Gets or sets the StringData.
        /// </summary>
        public string StringData
        {
            get
            {
                return this._stringData;
            }
        
            set
            {
                this._stringData = value;
                this.OnPropertyChanged("StringData");
            }
        }
      
        private string _stringData;
      
        /// <summary>
        /// Gets or sets the UnusualEntityId.
        /// </summary>
        public long UnusualEntityId
        {
            get
            {
                return this._unusualEntityId;
            }
        
            set
            {
                this._unusualEntityId = value;
                this.OnPropertyChanged("UnusualEntityId");
            }
        }
      
        private long _unusualEntityId;
      
        /// <summary>
        /// Gets or sets the ExtensionProperties.
        /// </summary>
        public ObservableCollection<CommerceProperty> ExtensionProperties
        {
            get
            {
                return this._extensionProperties;
            }
        
            set
            {
                this._extensionProperties = value;
                this.OnPropertyChanged("ExtensionProperties");
            }
        }
      
        private void ExtensionProperties_OnCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnPropertyChanged("ExtensionProperties");  
        }
    
        private ObservableCollection<CommerceProperty> _extensionProperties = new ObservableCollection<CommerceProperty>();
      
    }
    
    /// <summary>
    /// LATCOBasicDocumentTypeEntity entity class.
    /// </summary>
    [Microsoft.OData.Client.Key("UnusualEntityId")]
    [GeneratedCodeAttribute("Contoso.Commerce.RetailProxy.Extension", "1.0")]
    public class LATCOBasicDocumentTypeEntity : CommerceEntity
    { 
        /// 
        /// Initializes a new instance of the <see cref="LATCOBasicDocumentTypeEntity" /> class.
        /// 
        public LATCOBasicDocumentTypeEntity()
        {
            
            this._extensionProperties.CollectionChanged += ExtensionProperties_OnCollectionChanged;
        }
      
        /// <summary>
        /// Gets or sets the CheckDigitCal.
        /// </summary>
        public int CheckDigitCal
        {
            get
            {
                return this._checkDigitCal;
            }
        
            set
            {
                this._checkDigitCal = value;
                this.OnPropertyChanged("CheckDigitCal");
            }
        }
      
        private int _checkDigitCal;
      
        /// <summary>
        /// Gets or sets the Description.
        /// </summary>
        public string Description
        {
            get
            {
                return this._description;
            }
        
            set
            {
                this._description = value;
                this.OnPropertyChanged("Description");
            }
        }
      
        private string _description;
      
        /// <summary>
        /// Gets or sets the DocumentCod.
        /// </summary>
        public string DocumentCod
        {
            get
            {
                return this._documentCod;
            }
        
            set
            {
                this._documentCod = value;
                this.OnPropertyChanged("DocumentCod");
            }
        }
      
        private string _documentCod;
      
        /// <summary>
        /// Gets or sets the DocumentId.
        /// </summary>
        public string DocumentId
        {
            get
            {
                return this._documentId;
            }
        
            set
            {
                this._documentId = value;
                this.OnPropertyChanged("DocumentId");
            }
        }
      
        private string _documentId;
      
        /// <summary>
        /// Gets or sets the PlainTextDocumentType.
        /// </summary>
        public string PlainTextDocumentType
        {
            get
            {
                return this._plainTextDocumentType;
            }
        
            set
            {
                this._plainTextDocumentType = value;
                this.OnPropertyChanged("PlainTextDocumentType");
            }
        }
      
        private string _plainTextDocumentType;
      
        /// <summary>
        /// Gets or sets the IsAlphanumeric.
        /// </summary>
        public int IsAlphanumeric
        {
            get
            {
                return this._isAlphanumeric;
            }
        
            set
            {
                this._isAlphanumeric = value;
                this.OnPropertyChanged("IsAlphanumeric");
            }
        }
      
        private int _isAlphanumeric;
      
        /// <summary>
        /// Gets or sets the CampLong.
        /// </summary>
        public int CampLong
        {
            get
            {
                return this._campLong;
            }
        
            set
            {
                this._campLong = value;
                this.OnPropertyChanged("CampLong");
            }
        }
      
        private int _campLong;
      
        /// <summary>
        /// Gets or sets the Itau.
        /// </summary>
        public string Itau
        {
            get
            {
                return this._itau;
            }
        
            set
            {
                this._itau = value;
                this.OnPropertyChanged("Itau");
            }
        }
      
        private string _itau;
      
        /// <summary>
        /// Gets or sets the Davivienda.
        /// </summary>
        public string Davivienda
        {
            get
            {
                return this._davivienda;
            }
        
            set
            {
                this._davivienda = value;
                this.OnPropertyChanged("Davivienda");
            }
        }
      
        private string _davivienda;
      
        /// <summary>
        /// Gets or sets the BancoBogota.
        /// </summary>
        public string BancoBogota
        {
            get
            {
                return this._bancoBogota;
            }
        
            set
            {
                this._bancoBogota = value;
                this.OnPropertyChanged("BancoBogota");
            }
        }
      
        private string _bancoBogota;
      
        /// <summary>
        /// Gets or sets the ForeignDocument.
        /// </summary>
        public int ForeignDocument
        {
            get
            {
                return this._foreignDocument;
            }
        
            set
            {
                this._foreignDocument = value;
                this.OnPropertyChanged("ForeignDocument");
            }
        }
      
        private int _foreignDocument;
      
        /// <summary>
        /// Gets or sets the DocumentCodRE.
        /// </summary>
        public string DocumentCodRE
        {
            get
            {
                return this._documentCodRE;
            }
        
            set
            {
                this._documentCodRE = value;
                this.OnPropertyChanged("DocumentCodRE");
            }
        }
      
        private string _documentCodRE;
      
        /// <summary>
        /// Gets or sets the DataAreaId.
        /// </summary>
        public string DataAreaId
        {
            get
            {
                return this._dataAreaId;
            }
        
            set
            {
                this._dataAreaId = value;
                this.OnPropertyChanged("DataAreaId");
            }
        }
      
        private string _dataAreaId;
      
        /// <summary>
        /// Gets or sets the UnusualEntityId.
        /// </summary>
        public long UnusualEntityId
        {
            get
            {
                return this._unusualEntityId;
            }
        
            set
            {
                this._unusualEntityId = value;
                this.OnPropertyChanged("UnusualEntityId");
            }
        }
      
        private long _unusualEntityId;
      
        /// <summary>
        /// Gets or sets the ExtensionProperties.
        /// </summary>
        public ObservableCollection<CommerceProperty> ExtensionProperties
        {
            get
            {
                return this._extensionProperties;
            }
        
            set
            {
                this._extensionProperties = value;
                this.OnPropertyChanged("ExtensionProperties");
            }
        }
      
        private void ExtensionProperties_OnCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnPropertyChanged("ExtensionProperties");  
        }
    
        private ObservableCollection<CommerceProperty> _extensionProperties = new ObservableCollection<CommerceProperty>();
      
    }
    
}
  